# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(905, 649)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.wordlist = QtWidgets.QTreeView(Dialog)
        self.wordlist.setGeometry(QtCore.QRect(20, 90, 181, 511))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.wordlist.setFont(font)
        self.wordlist.setAutoFillBackground(False)
        self.wordlist.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.wordlist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wordlist.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.wordlist.setAlternatingRowColors(True)
        self.wordlist.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.wordlist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.wordlist.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.wordlist.setRootIsDecorated(False)
        self.wordlist.setObjectName("wordlist")
        self.label_wordlist = QtWidgets.QLabel(Dialog)
        self.label_wordlist.setGeometry(QtCore.QRect(20, 50, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label_wordlist.setFont(font)
        self.label_wordlist.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wordlist.setObjectName("label_wordlist")
        self.label_word = QtWidgets.QLabel(Dialog)
        self.label_word.setGeometry(QtCore.QRect(230, 70, 441, 21))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label_word.setFont(font)
        self.label_word.setTextFormat(QtCore.Qt.AutoText)
        self.label_word.setScaledContents(False)
        self.label_word.setAlignment(QtCore.Qt.AlignCenter)
        self.label_word.setObjectName("label_word")
        self.label_word_show = QtWidgets.QLabel(Dialog)
        self.label_word_show.setGeometry(QtCore.QRect(230, 100, 441, 21))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label_word_show.setFont(font)
        self.label_word_show.setText("")
        self.label_word_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_word_show.setObjectName("label_word_show")
        self.label_def = QtWidgets.QLabel(Dialog)
        self.label_def.setGeometry(QtCore.QRect(230, 130, 441, 20))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label_def.setFont(font)
        self.label_def.setAlignment(QtCore.Qt.AlignCenter)
        self.label_def.setObjectName("label_def")
        self.label_def_show = QtWidgets.QLabel(Dialog)
        self.label_def_show.setGeometry(QtCore.QRect(230, 150, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label_def_show.setFont(font)
        self.label_def_show.setText("")
        self.label_def_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_def_show.setWordWrap(True)
        self.label_def_show.setObjectName("label_def_show")
        self.label_samp = QtWidgets.QLabel(Dialog)
        self.label_samp.setGeometry(QtCore.QRect(230, 210, 441, 21))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label_samp.setFont(font)
        self.label_samp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_samp.setObjectName("label_samp")
        self.label_samp_show = QtWidgets.QLabel(Dialog)
        self.label_samp_show.setGeometry(QtCore.QRect(230, 240, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label_samp_show.setFont(font)
        self.label_samp_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_samp_show.setWordWrap(True)
        self.label_samp_show.setObjectName("label_samp_show")
        self.console_show_history = QtWidgets.QTextBrowser(Dialog)
        self.console_show_history.setGeometry(QtCore.QRect(230, 330, 631, 251))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.console_show_history.setFont(font)
        self.console_show_history.setObjectName("console_show_history")
        self.label_console = QtWidgets.QLabel(Dialog)
        self.label_console.setGeometry(QtCore.QRect(230, 310, 631, 21))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label_console.setFont(font)
        self.label_console.setAlignment(QtCore.Qt.AlignCenter)
        self.label_console.setObjectName("label_console")
        self.button_show_wordlist = QtWidgets.QPushButton(Dialog)
        self.button_show_wordlist.setGeometry(QtCore.QRect(15, 600, 191, 32))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.button_show_wordlist.setFont(font)
        self.button_show_wordlist.setObjectName("button_show_wordlist")
        self.button_quit = QtWidgets.QPushButton(Dialog)
        self.button_quit.setGeometry(QtCore.QRect(756, 600, 111, 32))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.button_quit.setFont(font)
        self.button_quit.setObjectName("button_quit")
        self.console = QtWidgets.QLineEdit(Dialog)
        self.console.setGeometry(QtCore.QRect(230, 580, 574, 21))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.console.setFont(font)
        self.console.setObjectName("console")
        self.button_help = QtWidgets.QPushButton(Dialog)
        self.button_help.setGeometry(QtCore.QRect(224, 600, 111, 32))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.button_help.setFont(font)
        self.button_help.setObjectName("button_help")
        self.check_code = QtWidgets.QCheckBox(Dialog)
        self.check_code.setGeometry(QtCore.QRect(800, 310, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.check_code.setFont(font)
        self.check_code.setChecked(False)
        self.check_code.setObjectName("check_code")
        self.button_clear = QtWidgets.QPushButton(Dialog)
        self.button_clear.setGeometry(QtCore.QRect(796, 576, 71, 32))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.button_clear.setFont(font)
        self.button_clear.setObjectName("button_clear")
        self.label_info = QtWidgets.QLabel(Dialog)
        self.label_info.setGeometry(QtCore.QRect(339, 605, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label_info.setFont(font)
        self.label_info.setText("")
        self.label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.combo_box_mode = QtWidgets.QComboBox(Dialog)
        self.combo_box_mode.setGeometry(QtCore.QRect(227, 306, 101, 30))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.combo_box_mode.setFont(font)
        self.combo_box_mode.setObjectName("combo_box_mode")
        self.combo_box_mode.addItem("")
        self.combo_box_mode.addItem("")
        self.combo_box_mode.addItem("")
        self.search_box = QtWidgets.QLineEdit(Dialog)
        self.search_box.setGeometry(QtCore.QRect(20, 70, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.search_box.setFont(font)
        self.search_box.setObjectName("search_box")
        self.check_more = QtWidgets.QCheckBox(Dialog)
        self.check_more.setGeometry(QtCore.QRect(800, 40, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.check_more.setFont(font)
        self.check_more.setObjectName("check_more")
        self.reload_selection_box = QtWidgets.QLineEdit(Dialog)
        self.reload_selection_box.setGeometry(QtCore.QRect(20, 24, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.reload_selection_box.setFont(font)
        self.reload_selection_box.setObjectName("reload_selection_box")
        self.button_reload = QtWidgets.QPushButton(Dialog)
        self.button_reload.setGeometry(QtCore.QRect(92, 20, 111, 32))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.button_reload.setFont(font)
        self.button_reload.setObjectName("button_reload")
        self.label_thesaurus = QtWidgets.QLabel(Dialog)
        self.label_thesaurus.setGeometry(QtCore.QRect(670, 70, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label_thesaurus.setFont(font)
        self.label_thesaurus.setTextFormat(QtCore.Qt.AutoText)
        self.label_thesaurus.setScaledContents(False)
        self.label_thesaurus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thesaurus.setObjectName("label_thesaurus")
        self.label_thesaurus_show = QtWidgets.QLabel(Dialog)
        self.label_thesaurus_show.setGeometry(QtCore.QRect(670, 100, 181, 191))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label_thesaurus_show.setFont(font)
        self.label_thesaurus_show.setText("")
        self.label_thesaurus_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thesaurus_show.setObjectName("label_thesaurus_show")
        self.actionread_in = QtWidgets.QAction(Dialog)
        self.actionread_in.setCheckable(False)
        self.actionread_in.setObjectName("actionread_in")

        self.retranslateUi(Dialog)
        self.combo_box_mode.setCurrentIndex(0)
        self.button_quit.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.console, self.button_show_wordlist)
        Dialog.setTabOrder(self.button_show_wordlist, self.button_quit)
        Dialog.setTabOrder(self.button_quit, self.console_show_history)
        Dialog.setTabOrder(self.console_show_history, self.wordlist)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AlphabetQs"))
        self.label_wordlist.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">WORD LIST</span></p></body></html>"))
        self.label_word.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">WORD</span></p></body></html>"))
        self.label_def.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">DEFINITION</span></p></body></html>"))
        self.label_samp.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">SAMPLE SENTENCE</span></p></body></html>"))
        self.label_samp_show.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.label_console.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">CONSOLE</span></p></body></html>"))
        self.button_show_wordlist.setText(_translate("Dialog", "SHOW"))
        self.button_quit.setText(_translate("Dialog", "QUIT"))
        self.button_help.setText(_translate("Dialog", "HELP"))
        self.check_code.setText(_translate("Dialog", "CODE"))
        self.button_clear.setText(_translate("Dialog", "CLEAR"))
        self.combo_box_mode.setCurrentText(_translate("Dialog", "SEARCH"))
        self.combo_box_mode.setItemText(0, _translate("Dialog", "SEARCH"))
        self.combo_box_mode.setItemText(1, _translate("Dialog", "RANDOM"))
        self.combo_box_mode.setItemText(2, _translate("Dialog", "ORDER"))
        self.search_box.setWhatsThis(_translate("Dialog", "Search Box"))
        self.search_box.setPlaceholderText(_translate("Dialog", "Search # or word"))
        self.check_more.setText(_translate("Dialog", "MORE"))
        self.button_reload.setText(_translate("Dialog", "RELOAD"))
        self.label_thesaurus.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">THESAURUS</span></p></body></html>"))
        self.actionread_in.setText(_translate("Dialog", "read_in"))

